dataset:
  name: chexpert
  source: local
  num_classes: 5
  task_type: multilabel
  image_size: 224
  class_names:
    - Atelectasis
    - Cardiomegaly
    - Consolidation
    - Edema
    - Pleural Effusion
  label_columns:
    - Atelectasis
    - Cardiomegaly
    - Consolidation
    - Edema
    - Pleural Effusion

  # Persistent OAK paths (scratch copies get purged; OAK survives).
  data_dir: /oak/stanford/groups/roxanad/bikia/processed_chexpert/combined_train_valid_chexpert_v1.0
  csv_path: /oak/stanford/groups/roxanad/bikia/processed_chexpert/explore_chexpert/train_valid_combined.csv
